import { MotionPressable, MotionReveal } from '@/components/motion/Motion';
import { useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { localDateKey, monthCells } from './query';
import { useJournalColors } from './theme';

export function DreamCalendar({ selectedDate, onSelect, dates = [], allowFuture = true, onMonthChange }: { selectedDate?: string; onSelect: (date: string) => void; dates?: string[]; allowFuture?: boolean; onMonthChange?: (month: string) => void }) {
  const colors = useJournalColors();
  const { fontScale } = useWindowDimensions();
  const cellHeight = Math.max(48, 24 * Math.min(fontScale, 2) + 16);
  const [month, setMonth] = useState(() => selectedDate ? new Date(`${selectedDate}T12:00:00`) : new Date());
  const changeMonth = (next: Date) => { setMonth(next); onMonthChange?.(localDateKey(next).slice(0, 7)); };
  const [picker, setPicker] = useState(false);
  const [year, setYear] = useState(month.getFullYear());
  const earliestYear = Math.min(new Date().getFullYear(), ...dates.map(date => Number(date.slice(0, 4))).filter(Number.isFinite));
  const years = Array.from({ length: Math.max(new Date().getFullYear() - earliestYear + 1, 10) }, (_, index) => new Date().getFullYear() - index);
  const marked = new Set(dates);
  const today = localDateKey(new Date());
  const cells = monthCells(month);
  return <MotionReveal subtle style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>
    <View style={styles.heading}>
      <MotionPressable haptic="selection" accessibilityRole="button" accessibilityLabel="Choose month and year" onPress={() => { setYear(month.getFullYear()); setPicker(true); }} style={styles.monthButton}><Text style={[styles.month, { color: colors.ink, flexShrink: 1 }]}>{month.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}</Text><Ionicons name="chevron-down" size={15} color={colors.muted} /></MotionPressable>
      <View style={styles.controls}>{[-1, 1].map(direction => <MotionPressable haptic="selection" key={direction} accessibilityRole="button" accessibilityLabel={direction < 0 ? 'Previous month' : 'Next month'} onPress={() => changeMonth(new Date(month.getFullYear(), month.getMonth() + direction, 1))} style={styles.arrow}><Ionicons name={direction < 0 ? 'chevron-back' : 'chevron-forward'} size={19} color={colors.accent} /></MotionPressable>)}</View>
    </View>
    <View style={styles.grid}>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, index) => <View key={index} style={[styles.cell, { minHeight: cellHeight }]}><Text maxFontSizeMultiplier={1.3} style={[styles.weekday, { color: colors.muted }]}>{day}</Text></View>)}</View>
    <MotionReveal key={localDateKey(month).slice(0, 7)} subtle>{Array.from({ length: cells.length / 7 }, (_, week) => <View key={week} style={styles.grid}>{cells.slice(week * 7, week * 7 + 7).map((date, index) => {
      const selected = date === selectedDate;
      const disabled = Boolean(date && !allowFuture && date > today);
      return <View key={date || `blank-${index}`} style={[styles.cell, { minHeight: cellHeight }]}>{date && <MotionPressable haptic="selection" accessibilityRole="button" accessibilityLabel={`${new Date(`${date}T12:00:00`).toLocaleDateString('en-GB', { dateStyle: 'full' })}${marked.has(date) ? ", dreams saved" : ""}`} accessibilityState={{ selected, disabled }} disabled={disabled} onPress={() => onSelect(date)} style={[styles.day, { minHeight: cellHeight - 4, backgroundColor: selected ? colors.accent : 'transparent' }, date === today && !selected && { borderWidth: 1, borderColor: colors.accent }, disabled && { opacity: .3 }]}><Text maxFontSizeMultiplier={2} style={[styles.dayText, { color: selected ? colors.background : colors.ink }]}>{Number(date.slice(-2))}</Text><View style={[styles.dot, { backgroundColor: marked.has(date) ? (selected ? colors.background : colors.accent) : 'transparent' }]} /></MotionPressable>}</View>;
    })}</View>)}</MotionReveal>
    <Modal visible={picker} transparent animationType="fade" onRequestClose={() => setPicker(false)}><View style={styles.overlay}><ScrollView style={[styles.picker, { backgroundColor: colors.surface, maxHeight: '90%' }]} contentContainerStyle={{ padding: 20 }}><View style={styles.heading}><Text style={[styles.month, { color: colors.ink }]}>Jump to a month</Text><MotionPressable haptic="selection" accessibilityRole="button" accessibilityLabel="Close month picker" onPress={() => setPicker(false)} style={styles.arrow}><Ionicons name="close" size={23} color={colors.muted} /></MotionPressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingBottom: 16 }}>{years.map(value => <MotionPressable haptic="selection" key={value} accessibilityRole="button" accessibilityState={{ selected: value === year }} onPress={() => setYear(value)} style={[styles.year, { backgroundColor: value === year ? colors.accentSoft : colors.background }]}><Text style={[styles.dayText, { color: value === year ? colors.accent : colors.muted }]}>{value}</Text></MotionPressable>)}</ScrollView><View>{Array.from({ length: 4 }, (_, row) => <View key={row} style={styles.grid}>{Array.from({ length: 3 }, (_, column) => { const index = row * 3 + column; return <MotionPressable haptic="selection" key={index} accessibilityRole="button" accessibilityLabel={new Date(year, index, 1).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })} onPress={() => { changeMonth(new Date(year, index, 1)); setPicker(false); }} style={[styles.monthOption, { backgroundColor: month.getMonth() === index && month.getFullYear() === year ? colors.accentSoft : colors.background }]}><Text style={[styles.dayText, { color: colors.ink }]}>{new Date(year, index, 1).toLocaleDateString('en-GB', { month: 'short' })}</Text></MotionPressable>; })}</View>)}</View><MotionPressable haptic="selection" accessibilityRole="button" onPress={() => { changeMonth(new Date()); setPicker(false); }} style={[styles.year, { alignSelf: 'center', marginTop: 18 }]}><Text style={[styles.dayText, { color: colors.accent }]}>This month</Text></MotionPressable></ScrollView></View></Modal>
  </MotionReveal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: '#100A2470', justifyContent: 'center', padding: 24 }, picker: { borderRadius: 26, width: '100%', maxWidth: 450, alignSelf: 'center' }, monthButton: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44 }, year: { minHeight: 44, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }, monthOption: { flex: 1, margin: 4, minHeight: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, card: { padding: 8, borderWidth: 1, borderRadius: 24 }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }, month: { fontFamily: 'Outfit_600SemiBold', fontSize: 18 }, controls: { flexDirection: 'row' }, arrow: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, grid: { flexDirection: 'row' }, cell: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center' }, weekday: { fontFamily: 'Outfit_500Medium', fontSize: 12 }, day: { width: '100%', minHeight: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, dayText: { fontFamily: 'Outfit_500Medium', fontSize: 17 }, dot: { height: 4, width: 4, borderRadius: 2, marginTop: 3 } });
