const email='founder@levites.app';
const contact=`<a href="mailto:${email}">${email}</a>`;
const controller=`LEVITES TECH LTD, company number 17059524, 71–75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ`;
const page=(slug,heading,description,intro,content)=>({slug,heading,title:`${heading} | The Dreamer`,description,intro,content,article:true,utility:true,category:slug==='privacy'||slug==='terms'?'Legal information':'Help & support'});
export const appPages=[
page('privacy','Privacy policy','Learn how The Dreamer handles journal entries, voice recordings, account information, AI processing, diagnostics, purchases, and your privacy rights.',
'This policy explains how The Dreamer, listed on the App Store as Dream Journal: Dream AI, handles your personal information. It covers the iPhone app, its cloud services, this website, and support requests.',
`<div class="callout"><strong>At a glance</strong><p>Your journal can contain personal information. Cloud features process journal content and recordings; optional AI features send relevant content to an AI service. Purchases are handled by Apple and RevenueCat. Current app builds use Sentry for crash and error diagnostics. Amplitude usage analytics have been removed from this version. This website has no advertising or analytics scripts.</p></div>
<nav class="toc" aria-label="Privacy policy contents"><a href="#controller">Who we are</a><a href="#data">Data and purposes</a><a href="#providers">Service providers</a><a href="#retention">Retention and deletion</a><a href="#rights">Your rights</a></nav>
<h2 id="controller">1. Who is responsible for your information?</h2><p>${controller}, is the controller of personal information processed to provide The Dreamer. Contact ${contact} for privacy questions or requests. Our registered address is also available in the <a href="https://find-and-update.company-information.service.gov.uk/company/17059524">official company register</a>.</p>
<h2 id="data">2. What information do we process, and why?</h2>
<div class="table-scroll"><table><thead><tr><th scope="col">Information</th><th scope="col">Purpose</th></tr></thead><tbody>
<tr><td>Dream entries, titles, dates, reflections, moods, tags, transcripts and generated summaries</td><td>Save, organise, search, sync, export and display your personal journal.</td></tr>
<tr><td>Voice recordings, duration and associated entry identifiers</td><td>Keep and play recordings and, when requested, transcribe them.</td></tr>
<tr><td>Guest/account identifiers, optional email address, sign-in verification and session information</td><td>Keep journals associated with the correct account, authenticate requests and recover an email-linked journal.</td></tr>
<tr><td>Purchase identifiers, subscription status, product and transaction information</td><td>Verify premium access and restore purchases. Apple processes payment details; the app does not ask for your full card number.</td></tr>
<tr><td>Device/app information, network information, errors and crash diagnostics</td><td>Operate and secure the service and diagnose faults. Third-party SDKs may assign device or installation identifiers.</td></tr>
<tr><td>Your support email, correspondence and attachments you choose to provide</td><td>Answer questions, resolve issues, handle privacy requests and maintain a record of the response.</td></tr>
</tbody></table></div>
<p>You provide journal content and support information directly. Some device, session, purchase and network information is generated automatically by the app, its service providers or ordinary network requests. Website requests reach Cloudflare, which processes request and network information to deliver and protect the site.</p>
<h2>3. AI transcription and summaries</h2><p>When you request a cloud transcription or AI summary, the relevant recording, transcript or written entry is sent to the service used by that version of the app. The current backend sends requested recordings to Cloudflare Workers AI Whisper Large v3 Turbo for transcription and requested written entries or transcripts to OpenAI GPT-6 Luna for summaries and journal metadata. Journal data and saved recordings remain stored on Cloudflare. Previous backend versions used OpenAI GPT-Transcribe or Cloudflare Workers AI; earlier app releases may use OpenAI for AI processing and Supabase for cloud storage. The provider used depends on the installed release and backend configuration.</p><p>AI output can be incomplete or inaccurate. It is intended for personal reflection, not diagnosis, prediction or a definitive dream interpretation. Avoid including other people’s private information or sensitive details you do not want processed. You can stop requesting AI processing and delete saved entries. Removing microphone permission stops future voice capture; it does not delete recordings you have already saved.</p><p>OpenAI describes how it handles API inputs and outputs in its <a href="https://developers.openai.com/api/docs/guides/your-data">API data-use documentation</a>. Cloudflare describes its handling of Workers AI inputs and outputs in its <a href="https://developers.cloudflare.com/workers-ai/platform/data-usage/">Workers AI data-use documentation</a>. We do not promise that all historical releases use the same provider, retention settings or infrastructure.</p>
<h2>4. Permissions and your choices</h2><ul><li><strong>Microphone:</strong> used for recordings you choose to make. Change access in iOS Settings.</li><li><strong>Notifications:</strong> used for optional dream reminders. Turn reminders off in the app or revoke notification permission in iOS Settings.</li><li><strong>Email recovery:</strong> adding an email is optional in versions that support guest journaling. A guest identity can still be associated with cloud journal data.</li><li><strong>Export and sharing:</strong> exports create a readable copy. When you choose a destination in the share sheet, that destination receives the information you share.</li></ul><p>The app does not require contacts, precise location or photo-library access for its core dream-journaling features. Device backups and exported copies are managed separately from our cloud journal.</p>
<h2>5. Our purposes and legal bases</h2><p>Where UK or European data-protection law applies, we process information needed to provide the journal, accounts, requested cloud features and purchases to perform our contract with you. We rely on legitimate interests for proportionate service security, fault diagnosis and support administration, and legal obligations where a record must be kept by law. Where consent is required for an optional feature, sensitive information or a particular form of analytics, that processing requires consent; consent can be withdrawn for future processing.</p><p>Dream entries may reveal health, beliefs or other sensitive information. You do not need to include such details to use a journal. Contact us if you want to understand or restrict processing of sensitive information you have already provided. Withdrawal does not affect processing that was lawful before withdrawal.</p>
<h2 id="providers">6. Service providers and sharing</h2><p>Service providers process information for the functions below. They are required to protect personal information under applicable law and their contractual obligations, and we require protection consistent with this policy. Their own policies explain their processing practices.</p>
<ul><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>: website/API hosting, journal database, private recording storage, authentication-email delivery and network protection.</li><li><a href="https://www.revenuecat.com/privacy/">RevenueCat</a>: subscription and entitlement management using account/purchase identifiers and purchase information.</li><li><a href="https://www.apple.com/legal/privacy/">Apple</a>: App Store distribution, payment processing, subscriptions, refunds and device services you choose to use.</li><li><a href="https://sentry.io/privacy/">Sentry</a>: production-app crash and error diagnostics, which may include device, network and contextual information.</li><li><a href="https://amplitude.com/privacy">Amplitude</a>: usage analytics in earlier app releases, including device/installation identifiers and usage information. It is removed from the current app source; older installed releases can still use it.</li><li><a href="https://openai.com/policies/privacy-policy/">OpenAI</a>: requested recording transcription and AI summaries using the relevant recording, written entry or transcript.</li><li><a href="https://supabase.com/privacy">Supabase</a>: storage and account functions in earlier releases. Historical cloud records are not automatically imported or erased by installing a newer release.</li><li>Email providers: process correspondence and delivery information when you contact support or receive an authentication message.</li></ul>
<p>Journal content is not published as a public feed. We do not sell dream entries or use them to serve personalised advertising. Information may be disclosed when necessary to comply with law, address security or fraud, protect rights, or transfer the service in a business transaction subject to appropriate safeguards.</p>
<h2>7. International processing and security</h2><p>Our providers operate internationally, and information may be processed outside your country, including in the United States. Where required, transfers are subject to an adequacy decision or appropriate contractual safeguards. Contact us for information about safeguards relevant to your request.</p><p>The current backend uses encrypted HTTPS connections, authenticated journal access and private audio storage. Access controls reduce unauthorised access; they are not a promise of end-to-end encryption. Neither a device nor a cloud service can be guaranteed completely secure. Keep your device protected and do not share sign-in codes.</p>
<h2 id="retention">8. Retention and deletion</h2><p>Journal and account information remains available for the service until you delete it or request removal, subject to technical and legal retention needs. We do not impose a universal automatic expiry on journal entries. In the current backend, entry deletion removes readable content and retains a minimal deletion marker to prevent an interrupted sync from recreating it. Account deletion removes the account and associated active database records; recording files enter a cleanup queue that retries failed removals.</p><p>Recordings pending cleanup, service-provider backups, security records, support correspondence and purchase/accounting records may remain for the time needed to complete deletion, resolve an issue, protect the service, or satisfy legal requirements. Not all providers use the same retention period. Contact us for the retention details relevant to your data; we do not promise immediate deletion of every provider-held record.</p><p>Deleting the app alone does not delete cloud data or cancel subscriptions. Exports, device backups and copies you shared elsewhere are outside the cloud deletion process. See <a href="/delete-account">account and data deletion</a> for the current app steps and help with earlier versions or guest journals.</p>
<h2 id="rights">9. Your privacy rights</h2><p>Depending on your location and circumstances, you may request access, correction, erasure, restriction, portability, or object to processing. You may also withdraw consent where processing relies on it. Contact ${contact}, describe your request and identify the account email if you have one. We may need proportionate verification of ownership before releasing or deleting information. Do not send passwords, verification codes or unnecessary journal content.</p><h3>Your right to object</h3><p>You can object to processing based on legitimate interests, including relevant usage analysis. Contact us at the email above and tell us which processing you object to; we assess the request under applicable law.</p><p>We handle requests within applicable statutory time limits, normally within one month for UK GDPR requests, with any permitted extension explained. If you are in the UK, you can complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>; elsewhere you may contact your local data-protection authority. These rights are subject to the conditions and exceptions in applicable law.</p>
<p>AI summaries do not make decisions about you with legal or similarly significant effects. Providing an email is optional for guest capture in supported versions; account recovery requires an email. Cloud features need the content and identifiers necessary to fulfil the request.</p><h2>10. Children and age requirements</h2><p>The service is a general-purpose personal journal and is not designed specifically for children. Follow the age rating shown in your local App Store and any legal requirements for parental authorisation. If you believe a child’s information was collected without required authorisation, contact us so we can investigate and take appropriate action.</p>
<h2>11. Website storage and external links</h2><p>This marketing website does not load analytics, advertising or tracking scripts and does not provide a journal login or collect dreams through a form. Cloudflare may process technical request information to deliver and protect it. The app uses device storage and session credentials for journal/authentication functions. Visiting the App Store, provider policies or another external service is governed by that service’s policies.</p>
<h2>12. Changes and contact</h2><p>This policy is effective from 8 October 2026. We publish updates here with a new date and provide further notice where required for a material change. For privacy questions, contact ${contact} or write to ${controller}.</p>`),
page('terms','Terms of use','Read The Dreamer terms covering journal content, AI summaries, subscriptions, cancellation, acceptable use, account deletion, and Apple’s standard app license.',
'These terms describe use of The Dreamer, available on the App Store as Dream Journal: Dream AI, and this website. The service is provided by LEVITES TECH LTD.',
`<h2>1. Your agreement and the app license</h2><p>Use the service only if you can enter a valid agreement under applicable law, or have the required parent or guardian authorisation. The iOS app is licensed under <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple’s Standard Licensed Application End User License Agreement</a>. These service terms apply alongside that license and applicable App Store terms. If they conflict, the Apple license governs the app license, and mandatory consumer law continues to apply.</p>
<h2>2. Your journal and account</h2><p>You retain ownership of the content you provide. You authorise us and our service providers to process it as needed to save, sync, display, transcribe, summarise, export and support the features you request, as described in the <a href="/privacy">privacy policy</a>. This does not give us ownership of your journal or permission to publish it as a public feed.</p><p>Provide accurate account information where requested and protect your device and sign-in credentials. An email-linked account can support recovery; a guest journal may be difficult to recover if the device or session is lost. Keep an export of anything important. Do not share verification codes.</p>
<h2>3. AI content and personal reflection</h2><p>AI transcripts and summaries may contain errors, omissions or assumptions. Check them against your own memory before relying on them. The app is a personal journal, not a medical, psychological or therapeutic service. It does not diagnose conditions, predict events or establish a definitive meaning for a dream. You decide whether an output is useful and what to retain.</p>
<h2>4. Purchases and subscriptions</h2><p>The app is free to download and may offer paid features through Apple in-app purchases. Before subscribing, review the exact product, local price, billing interval, included features and any trial or introductory conditions shown in the app and Apple’s confirmation. Available packages may change and differ by country or version.</p><p>Auto-renewing subscriptions renew unless you cancel according to the terms shown by Apple. Apple generally requires cancellation at least 24 hours before the current period ends. Where offered, a trial converts to the paid subscription unless cancelled before its stated deadline. A trial is not guaranteed for every account or offer.</p><p>Manage cancellation in iPhone Settings → your name → Subscriptions. Deleting the app or account does not cancel billing. Restore an existing eligible purchase using Restore Purchases in the app. Refund eligibility and requests are handled by Apple and applicable law; see <a href="/subscriptions">subscription and billing help</a>.</p>
<h2>5. Acceptable use</h2><p>Do not use the service to break the law, infringe another person’s rights, upload content you have no right to process, distribute harmful code, bypass account or purchase controls, or interfere with the service. Respect other people’s privacy when describing them in a journal. We may restrict access where reasonably necessary to address abuse, security or legal requirements, while respecting applicable rights.</p>
<h2>6. Availability and changes</h2><p>Features depend on the installed app version, device permissions, connectivity, store availability and any premium entitlement. Cloud and AI services may be interrupted. We may maintain or update the service and will give notice where law requires it. We do not promise that every processing request will succeed or that the service is permanently uninterrupted.</p>
<h2>7. Deletion and ending use</h2><p>You can stop using the service. Export content you want to keep before deleting entries or an account. Follow the <a href="/delete-account">deletion guide</a> for the current app flow and support options. Cancellation and refunds for purchases are separate from journal/account deletion.</p>
<h2>8. Responsibility and your statutory rights</h2><p>Nothing in these terms removes rights or remedies that cannot be excluded by law, including applicable consumer guarantees. We do not exclude liability for fraud, fraudulent misrepresentation, death or personal injury caused by negligence, or another liability that law does not permit us to exclude. Other app-license warranty and responsibility provisions are set out in Apple’s standard license.</p>
<h2>9. Applicable law and disputes</h2><p>These service terms are governed by the law of England and Wales, subject to any mandatory consumer protections and rights to bring a claim in your country of residence. Contact support first if you want help resolving a service issue.</p>
<h2>10. Contact and changes to these terms</h2><p>${controller}. Contact ${contact}. These terms are effective from 8 October 2026. Updates are published here, with further notice or agreement obtained where required by applicable law.</p>`),
page('support','Help & support','Get help with The Dreamer for iPhone: recording, syncing, AI summaries, email recovery, restoring purchases, subscriptions, and deleting an account.',
'Find help for The Dreamer, listed as Dream Journal: Dream AI on the App Store. Choose a topic below, or contact the publisher’s support email.',
`<div class="help-grid"><a href="/subscriptions"><strong>Subscriptions & purchases</strong><span>Restore, cancel, or request a refund.</span></a><a href="/delete-account"><strong>Account & data deletion</strong><span>Export first, then remove your information.</span></a><a href="/privacy"><strong>Privacy & your data</strong><span>Understand cloud, AI and diagnostics.</span></a><a href="/contact"><strong>Contact support</strong><span>Get help with an issue in the app.</span></a></div>
<h2>My recording will not start</h2><p>Check that microphone permission is enabled for Dream AI in iOS Settings. Close any other app using the microphone and retry. If voice access requires Premium in your installed version, check your current entitlement or restore purchases. You can still capture the dream in writing while troubleshooting.</p>
<h2>A transcription or summary failed</h2><p>Check your connection and current premium access, then use Retry or restart processing if your installed version offers it. Avoid repeatedly starting the same request. In versions with local draft saving, your original entry can remain available while cloud processing retries. Do not delete an entry you want to preserve just to restart AI.</p>
<h2>My dream has not synced</h2><p>Return to a stable connection and reopen the journal. Check whether the app shows a pending sync or retry message. Local entries, drafts and cloud status depend on your installed version. Keep the app installed and export accessible entries before making changes that could remove device data.</p>
<h2>I cannot find my journal on another device</h2><p>In versions with guest journaling, add an email using Settings → Sign in with email on the original device, then verify the email code. Use the same email to recover that journal. A guest session without an email may not be recoverable from another device. Earlier releases may use a different account system; contact support before deleting the old app or journal.</p>
<h2>My sign-in code has not arrived</h2><p>Check the address and spam/junk folder. Use the most recent requested code, and allow time between requests. Do not send a code to support. If delivery continues to fail, include the account email and the approximate request time when reporting the issue.</p>
<h2>Premium is missing after a purchase</h2><p>Use the same Apple Account that made the purchase, then open Settings → Restore purchases in the app. Check iPhone Settings → your name → Subscriptions to confirm the subscription is active. If access still does not return, contact support with the product name and a redacted receipt or transaction reference.</p>
<h2>How do I export my dreams?</h2><p>In the current app, open Settings → Export my dreams and choose a destination in the share sheet. Store that copy somewhere you control. The readable export is separate from an account backup and may not include audio files. Features and labels can differ in older releases.</p>
<h2>Reminders are not appearing</h2><p>Check the app’s reminder setting and chosen time, then iOS notification permissions and Focus settings. Reminders are optional. You can turn them off in the app or iOS Settings.</p>
<h2>Contact support</h2><p>Email ${contact} with “Dreamer support” in the subject. Include your app version, iPhone model, iOS version, what happened and any error message. If useful, add a screenshot with private journal content removed. Do not include passwords, sign-in codes or payment-card details.</p><p>For privacy requests or a deletion issue, see <a href="/delete-account">account and data deletion</a> and the <a href="/privacy#rights">privacy-rights section</a>. The provider is ${controller}.</p>`),
page('delete-account','Account & data deletion','Learn how to export dreams, delete an email account and journal in The Dreamer, request guest or legacy data removal, and cancel a subscription separately.',
'You can remove your journal and account information. Export anything you want to keep first. Deletion is separate from cancelling an App Store subscription.',
`<div class="callout"><strong>Before you delete</strong><p>Account deletion cannot be undone. An export is a separate copy you control. Deleting your account or removing the app does not cancel an App Store subscription: <a href="/subscriptions">manage your subscription separately</a>.</p></div>
<h2>Delete an email account in the current app</h2><ol><li>Open The Dreamer and go to <strong>Settings</strong>.</li><li>If you want a readable copy, choose <strong>Export my dreams</strong> first.</li><li>Under <strong>Your account</strong>, choose <strong>Delete my account</strong>.</li><li>Read the confirmation, then choose <strong>Delete account & journal</strong> to proceed.</li><li>Wait for the app to confirm the result. If it reports a cleanup problem, keep the message and contact support.</li></ol><p>This flow is available for email accounts in the current app source. Labels and availability can differ in an older installed release. If you cannot find the option, update the app if an update is available, or contact support for help removing the data associated with that release.</p>
<h2>What is removed?</h2><p>The current deletion flow removes the account and its active cloud journal records and sessions, then queues associated cloud recordings for removal. Failed recording cleanup is retried. The app also attempts to clear the deleted account’s journal, draft and sign-in information from that device; it reports a warning if local cleanup could not finish.</p><p>Copies exported or shared elsewhere, device backups, Apple purchase records and some diagnostic, security, support or legally required records are separate. Third-party records can have their own retention periods. See the <a href="/privacy#retention">privacy policy’s retention section</a> for details.</p>
<h2>Delete individual dreams</h2><p>Use the entry’s delete action where available in your installed app. In the current backend, deletion removes readable content and queues associated audio cleanup. A minimal deletion marker helps prevent interrupted sync operations from recreating the entry.</p>
<h2>Guest journals and earlier app releases</h2><p>A guest journal may be stored under a device/session identity without an email. The current email-account deletion screen is not shown for guest users. Do not assume uninstalling the app removes associated cloud data. For guest data or data held by an earlier release, contact ${contact} with the subject “Dreamer data deletion” and describe the installed version and your access to the original device.</p><p>For an email account, provide the account email. For a guest journal, do not uninstall or reset the app before discussing ownership verification if you want cloud removal. We may need proportionate proof of control of the original account or session. Do not send passwords, verification codes, or the contents of your dreams as proof.</p>
<h2>A problem with deletion?</h2><p>Email ${contact}, include the app version and error message, and say whether you use an email account or a guest journal. A support email does not automatically delete anything. We verify ownership before acting on a request and handle it within applicable legal time limits. No support contact is required for the current in-app email-account deletion flow.</p>`),
page('subscriptions','Subscriptions & billing','Manage Dream AI subscriptions, restore Premium access, cancel renewals, understand trial terms, and request App Store refunds without deleting your journal.',
'Dream Journal: Dream AI is free to download and offers optional in-app subscriptions. Apple handles App Store billing; RevenueCat helps the app verify premium access.',
`<h2>Review the current offer</h2><p>Check the in-app paywall and Apple’s confirmation for your local price, billing interval, premium features and any trial or introductory conditions. Weekly and annual packages may be offered. Not every package or trial is available to every account or country. The website does not quote an unverified universal price.</p>
<h2>Cancel an App Store subscription</h2><ol><li>Open <strong>Settings</strong> on your iPhone.</li><li>Tap <strong>your name</strong>, then <strong>Subscriptions</strong>.</li><li>Select <strong>Dream AI</strong> or <strong>Dream Journal: Dream AI</strong>.</li><li>Tap <strong>Cancel Subscription</strong> or <strong>Cancel Free Trial</strong>, if available, and follow Apple’s instructions.</li></ol><p>You can also open <a href="https://apps.apple.com/account/subscriptions">Apple’s subscription management page</a>. If no cancellation option appears, check the expiry information and the Apple Account used for the purchase. See <a href="https://support.apple.com/118428">Apple’s cancellation instructions</a>.</p>
<h2>Renewals and trials</h2><p>Auto-renewing subscriptions continue until cancelled under the terms shown by Apple. Apple generally requires cancellation at least 24 hours before a period ends. A trial, where offered, converts to the disclosed paid subscription unless cancelled by its stated deadline. After cancellation, access normally continues until the expiry shown by Apple; trial access may be handled differently under Apple’s terms.</p>
<h2>Restore Premium access</h2><p>Use the Apple Account that purchased the subscription and select Settings → Restore purchases in the app. Restore does not make a new purchase. If the subscription is active but access is missing, contact <a href="/support">support</a> with the product name and a redacted transaction reference. Never send full payment details.</p>
<h2>Request a refund</h2><p>Visit <a href="https://reportaproblem.apple.com/">reportaproblem.apple.com</a> to request a refund for an Apple-billed purchase. Apple determines eligibility under its policies and applicable law. The developer cannot promise a refund or cancel Apple billing on your behalf.</p>
<h2>Deleting the app or account</h2><p>Neither action cancels a subscription. Cancel renewal in Apple’s subscription settings separately. If you also want to remove your information, follow <a href="/delete-account">account and data deletion</a>. Keep any journal export you need before deleting.</p>
<h2>Questions about a charge?</h2><p>First check the Apple purchase history and subscription list for the Apple Account used. Contact ${contact} if you need help with access inside the app. See our <a href="/terms">terms of use</a> and Apple’s purchase terms for the applicable conditions.</p>`),
page('contact','Contact The Dreamer','Contact LEVITES TECH LTD for Dreamer app support, privacy questions, purchase-access issues, or account-deletion help, with guidance on what to include.',
'The Dreamer is published by LEVITES TECH LTD. For help with Dream Journal: Dream AI, use the company’s support email below.',
`<div class="callout"><h2 style="margin-top:0">Email support</h2><p>${contact}<br>Subject: Dreamer support</p></div><h2>Help us understand the issue</h2><p>Include your app version, iPhone model, iOS version, the steps that led to the issue, and any error message. Include the account email only when relevant. Remove dream text and other personal details from screenshots unless you choose to share them for a specific support need.</p><p>Do not send passwords, sign-in codes or full payment-card details. We do not ask you to pay a separate fee to request help or exercise privacy rights.</p><h2>Choose a topic</h2><ul><li><a href="/support">General app help</a></li><li><a href="/subscriptions">Purchases, cancellation and refunds</a></li><li><a href="/delete-account">Account and data deletion</a></li><li><a href="/privacy#rights">Privacy rights and data requests</a></li><li><a href="/terms">Terms of use</a></li></ul><h2>Publisher and postal address</h2><p>${controller}.</p><p><a href="https://find-and-update.company-information.service.gov.uk/company/17059524">View our company registration</a>.</p>`)
];
